### ISSUE TITLE
On Light theme footer titles color are not changing

### ISSUE THREAD

**Issue by saadman-galib** [programming-for-career/cs-resources#5]
**Describe the bug**
On Light theme footer titles colors are not changing

**To Reproduce**

1. Go to Home page
2. Scroll to footer
3. Must change the theme mode to light

**Expected behavior**
Footer title colors must be synced with the theme mode

**Screenshots**
![image](https://github.com/user-attachments/assets/3c30a76b-d3ce-4545-b027-a23609114abd)

**Comment by saadman-galib** [comment]
I am interested to work on this issue

**Comment by maruf-pfc** [comment]
> I am interested to work on this issue

Sure :heart: 
Go to this [file](https://github.com/programming-for-career/cs-resources/blob/main/theme.config.tsx) and update the footer tailwind CSS part for light mode

**Comment by maruf-pfc** [comment]
After forking this repository create a new branch `develop` and then do everything inside the develop branch. 
After that push the code to GitHub and send a PR
