### ISSUE TITLE
There is no default formatter config file like prettier mentioning default spacing on format

### ISSUE THREAD

**Issue by saadman-galib** [programming-for-career/cs-resources#8]
There is no default formatter config file like prettier mentioning default spacing on format

I am interested to work on this issue

**Comment by maruf-pfc** [comment]
> There is no default formatter config file like prettier mentioning default spacing on format
> 
> I am interested to work on this issue

Do you want to add a prettier config file to format all the documents?

**Comment by saadman-galib** [comment]
> Do you want to add a prettier config file to format all the documents?

Yes, I am interested. I guess, default tabWidth 2 would be good.

**Comment by maruf-pfc** [comment]
> > Do you want to add a prettier config file to format all the documents?
> 
> Yes, I am interested. I guess, default tabWidth 2 would be good.

Okay then add the config file.
